sudo: required
dist: trusty
group: edge

env:
  global:
    - MAVEN_SKIP_RC=true
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

#language: android
jdk:
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
android:
  components:
    - build-tools-19.0.3
    - android-19
#    - sys-img-armeabi-v7a-android-19
#    - extra
#    - add-on

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

